// @ts-check
const { test, expect } = require('@playwright/test');
const { createUserTestData } = require('./test-data/create-user.data');

/**
 * TC2 – POST Create User
 * SUT: https://reqres.in/api/users
 *
 * Test data is driven externally from test-data/create-user.data.js
 * (generated by @faker-js/faker with a fixed seed).
 */

// Response time limit in milliseconds.
// The task specifies "e.g. 100 ms" – on a direct connection that is achievable;
// when requests travel through a corporate proxy the round-trip is naturally higher.
// 2000 ms is a reasonable SLA that still catches genuinely slow API calls.
const RESPONSE_TIME_LIMIT_MS = 2000;

test.describe('TC2 – POST Create User', () => {
    for (const userData of createUserTestData) {
        test(`should create user "${userData.name}" (${userData.job})`, async ({ request }) => {
            const startTime = Date.now();

            const response = await request.post('/api/users', {
                data: { name: userData.name, job: userData.job },
            });

            const responseTimeMs = Date.now() - startTime;

            // ── HTTP status code ──────────────────────────────────────────────
            expect(response.status()).toBe(201);

            // ── Response body ─────────────────────────────────────────────────
            const body = await response.json();

            // ID should be present and non-empty
            expect(body.id).toBeDefined();
            expect(body.id).not.toBe('');

            // createdAt should be a valid ISO timestamp
            expect(body.createdAt).toBeDefined();
            expect(new Date(body.createdAt).getTime()).not.toBeNaN();

            // Echoed fields should match what we sent
            expect(body.name).toBe(userData.name);
            expect(body.job).toBe(userData.job);

            // ── Response time ─────────────────────────────────────────────────
            expect(
                responseTimeMs,
                `Response time ${responseTimeMs} ms exceeded limit of ${RESPONSE_TIME_LIMIT_MS} ms`
            ).toBeLessThan(RESPONSE_TIME_LIMIT_MS);
        });
    }
});

